<a href="https://colab.research.google.com/github/sanjarberdimurodov19915-dev/ai_foundation/blob/main/pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

In [6]:
print(pd.__version__)

2.2.3

In [7]:
mydataset = {
  'cars': ["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Mersades", "Tayota"],
  'counts': [3, 7, 2, 8, 1, 9, 3]
}

print(mydataset)
print('===========================')

df = pd.DataFrame(mydataset)

print(df)

{'cars': ['BMW', 'Volvo', 'Ford', 'Tesla', 'Ferrari', 'Mersades', 'Tayota'], 'counts': [3, 7, 2, 8, 1, 9, 3]}
===========================
       cars  counts
0       BMW       3
1     Volvo       7
2      Ford       2
3     Tesla       8
4   Ferrari       1
5  Mersades       9
6    Tayota       3

In [10]:
df.head() # table boshidan default holatda 5 ta ma'lumot o'qib beradi, agar qavs ichiga son qo'ysak o'shancha miqdordagi ma'lumotni olib beradi,
# misol uchun 100 qo'ysak boshidan 100 ta oladi, sonlarni oldidan - qo'yilsa, oxiridan shuncha ma'lumotni olib tashlab ko'rsatadi, o qo'ysa hech narsa chiqmaydi

      cars  counts
0      BMW       3
1    Volvo       7
2     Ford       2
3    Tesla       8
4  Ferrari       1

In [11]:
df.tail() # head metodining teskarisi, oxiridan oladi

       cars  counts
2      Ford       2
3     Tesla       8
4   Ferrari       1
5  Mersades       9
6    Tayota       3

In [12]:
df.shape # property shapeni ko'rsatadi

(7, 2)

In [ ]:
df.columns  # data column indexlar bo'yicha nomlarini chiqaradi, hamda datatypeni aniqlaydi

In [13]:
df.dtypes  # tabledagi har bir columnni datatypeni aniqlaydi

cars      object
counts     int64
dtype: object

In [14]:
print(df)

       cars  counts
0       BMW       3
1     Volvo       7
2      Ford       2
3     Tesla       8
4   Ferrari       1
5  Mersades       9
6    Tayota       3

In [16]:
df.describe(include="all")  # numerical columns only, shu datani statistikasini aniqlab beradi

       cars    counts
count     7  7.000000
unique    7       NaN
top     BMW       NaN
freq      1       NaN
mean    NaN  4.714286
std     NaN  3.199702
min     NaN  1.000000
25%     NaN  2.500000
50%     NaN  3.000000
75%     NaN  7.500000
max     NaN  9.000000

In [20]:
df.iloc[0]  # hohlagan indexdagi ma'lumotlarni topib beradi, ma'lum bir oraliqdagi indexlarni ham belgilashimiz mumkin

cars      BMW
counts      3
Name: 0, dtype: object

In [23]:
df.loc[:, "cars"] # bizdan 2 ta ma'lumot kutadi, va biz kirtigan columndagi ma'lumotlarni olib kelib beradi,
# birinchi qiymatga son kiritsak, o'sha qatordagi ma'lumotni olib keladi, bir vaqtning o'zida bir nechta ma'lumotlarni ham olib keladi

0         BMW
1       Volvo
2        Ford
3       Tesla
4     Ferrari
5    Mersades
6      Tayota
Name: cars, dtype: object

In [26]:
df['counts'] > 3 # to'liq jadvalni  3 dan katta va kichiklarga ajratib boolean qaytaradi
df[df['counts'] > 3] # bu bizga faqat 3 dan katta bo'lgan qismini jadval ko'rinishida qaytaradi
# =, <=, >=, != conditionlarini ham ishlata olamiz

       cars  counts
1     Volvo       7
3     Tesla       8
5  Mersades       9

In [28]:
df[df["cars"] == "BMW"] # ma'lumotni izlash uchun foydalanamiz

  cars  counts
0  BMW       3

In [30]:
# df.mean(numeric_only=True) # faqat raqamlardan tashkil topgan columni mean qiymatini olib beradi
df["counts"].mean()

np.float64(4.714285714285714)

In [31]:
df.sum()

cars      BMWVolvoFordTeslaFerrariMersadesTayota
counts                                        33
dtype: object

In [32]:
df.min()

cars      BMW
counts      1
dtype: object

In [33]:
df.max()

cars      Volvo
counts        9
dtype: object

In [34]:
df.median(numeric_only=True) # middle valueni olib beradi

counts    3.0
dtype: float64

In [35]:
df.count() # None va NaN qiymatlarni izlaydi

cars      7
counts    7
dtype: int64

In [36]:
df.std(numeric_only=True) # standart deviationni hisoblab beradi

counts    3.199702
dtype: float64

In [37]:
data_with_missing = {
    "cars": ["BMW", "Volvo", None, "Tesla", "Ferrari", None, "Tayota"],
    "counts": [3, 7, None, 8, 1, 9, None ]
}

df_missing = pd.DataFrame(data_with_missing)
print(df_missing)

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2     None     NaN
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6   Tayota     NaN

In [39]:
# df_missing.isnull() # boolean qaytaradi, jadvaldagi bor ma'lumotni false, yo'q ma'lumotni true qaytaradi
df_missing.isnull().sum() # har bir columnda nechta data missingligini aniqlab beradi

cars      2
counts    2
dtype: int64

In [40]:
df_missing.dropna() # bo'sh qatorlarni jadvaldan o'chirib beradi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0

In [41]:
df_missing.dropna(how="all") # barcha qiymatlari bo'sh bo'lgan qatorni o'chiradi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0
6   Tayota     NaN

In [42]:
df_missing.dropna(axis=1) # ma'lumoti bo'sh bo'lgan barcha columnlarni o'chiradi

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [43]:
df_missing.dropna(subset=['counts']) # berilgan columnigina tekshiradi va unda biror ma'lumot kam bo'lsa shuni tashlab yuboradi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
3    Tesla     8.0
4  Ferrari     1.0
5     None     9.0

In [44]:
df_missing.fillna(0) # bo'sh qatorlarga biz bergan argumentni yozadi

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2        0     0.0
3    Tesla     8.0
4  Ferrari     1.0
5        0     9.0
6   Tayota     0.0

In [45]:
df_missing.fillna({"cars": "unknown", "counts": 0}) # kerakli columnlarga alohida missing ma'lumotlarni to'ldirish

      cars  counts
0      BMW     3.0
1    Volvo     7.0
2  unknown     0.0
3    Tesla     8.0
4  Ferrari     1.0
5  unknown     9.0
6   Tayota     0.0

In [53]:
# df = pd.read_csv("Titanic-Dataset.csv")

# df.head()

df = pd.read_excel("test.xlsx")

df.tail()

# df = pd.read_json("Titanic-Dataset.json")

,Unnamed: 0,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [50]:
df.to_excel("test.xlsx")

In [54]:
# Series => 1D arraylar bilan ishlashda ishlatiladi
cars = pd.Series(["BMW", "Volvo", "Ford", "Tesla", "Ferrari", "Mersades", "Tayota"])
print(cars)

0         BMW
1       Volvo
2        Ford
3       Tesla
4     Ferrari
5    Mersades
6      Tayota
dtype: object

In [55]:
cars_series = data_with_missing['cars']
print(cars_series)

['BMW', 'Volvo', None, 'Tesla', 'Ferrari', None, 'Tayota']